import random

# Define your list of movies with weights
    
movies_with_weights = [
    {"movie": "20,000 Leagues Under the Sea", "weight": 1},
    {"movie": "2001: A Space Odyssey", "weight": 1},
    {"movie": "300", "weight": 1},
    {"movie": "8 Mile", "weight": 1},
    {"movie": "A Beautiful Mind", "weight": 1},
    {"movie": "A Christmas Story", "weight": 1},
    {"movie": "A Nightmare on Elm Street (2010)", "weight": 1},
    {"movie": "A Scanner Darkly", "weight": 1},
    {"movie": "Alice in Wonderland (2010)", "weight": 1},
    {"movie": "Alien: Covenant", "weight": 1},
    {"movie": "Almost Famous", "weight": 1},
    {"movie": "American Beauty", "weight": 1},
    {"movie": "American Psycho", "weight": 1},
    {"movie": "Apocalypoto", "weight": 1},
    {"movie": "Arrival", "weight": 1},
    {"movie": "August Rush", "weight": 1},
    {"movie": "Back to the Future", "weight": 1},
    {"movie": "Back to the Future II", "weight": 1},
    {"movie": "Back to the Future Part III", "weight": 1},
    {"movie": "Baraka", "weight": 1},
    {"movie": "Batman Begins", "weight": 1},
    {"movie": "Being John Malcovich", "weight": 1},
    {"movie": "Big", "weight": 1},
    {"movie": "Big Hero 6", "weight": 1},
    {"movie": "Blade Runner 2049", "weight": 1},
    {"movie": "Blade Runner: The Final Cut", "weight": 1},
    {"movie": "Boiler Room", "weight": 1},
    {"movie": "Bridge to Tarabithia", "weight": 1},
    {"movie": "Constantine", "weight": 1},
    {"movie": "Contact", "weight": 1},
    {"movie": "Divergent", "weight": 1},
    {"movie": "Donnie Darko", "weight": 1},
    {"movie": "Dr. Seuss' How the Grinch Stole Christmas", "weight": 1},
    {"movie": "Dracula Untold", "weight": 1},
    {"movie": "Dune", "weight": 1},
    {"movie": "Eternal Sunshine of the spotless mind", "weight": 1},
    {"movie": "Ex Machina", "weight": 1},
    {"movie": "Eyes Wide Shut", "weight": 1},
    {"movie": "Fern Gully", "weight": 1},
    {"movie": "Fight Club", "weight": 1},
    {"movie": "Forrest Gump", "weight": 1},
    {"movie": "Get Rich Or Die Tryin'", "weight": 1},
    {"movie": "Gladiator", "weight": 1},
    {"movie": "Gone in Sixty Seconds", "weight": 1},
    {"movie": "Good Will Hunting", "weight": 1},
    {"movie": "Goodfellas", "weight": 1},
    {"movie": "Grandma's Boy UNRATED", "weight": 1},
    {"movie": "Guardians of the Galaxy", "weight": 1},
    {"movie": "Hardball", "weight": 1},
    {"movie": "Harry Potter and the Chamber of Secrets", "weight": 1},
    {"movie": "Harry Potter and the Deathly Hallows: Part 1", "weight": 1},
    {"movie": "Harry Potter and the Deathly Hallows: Part 2", "weight": 1},
    {"movie": "Harry Potter and the Goblet of Fire", "weight": 1},
    {"movie": "Harry Potter and the Half-Blood Prince", "weight": 1},
    {"movie": "Harry Potter and the Order of the Phoenix", "weight": 1},
    {"movie": "Harry Potter and the Prisoner of Azkaban", "weight": 1},
    {"movie": "Harry Potter and the Sorcerer's Stone", "weight": 1},
    {"movie": "Hellboy", "weight": 1},
    {"movie": "Home Alone", "weight": 1},
    {"movie": "Home Alone 2: Lost In New York", "weight": 1},
    {"movie": "Howl's Moving Castle", "weight": 1},
    {"movie": "Inception", "weight": 1},
    {"movie": "Incident in a Ghostland", "weight": 1},
    {"movie": "Independence Day", "weight": 1},
    {"movie": "Inglorious Basterds", "weight": 1},
    {"movie": "Inside Job", "weight": 1},
    {"movie": "Interstellar", "weight": 1},
    {"movie": "IP Man", "weight": 1},
    {"movie": "Iron Giant", "weight": 1},
    {"movie": "IT", "weight": 1},
    {"movie": "IT Chapter Two", "weight": 1},
    {"movie": "It Follows", "weight": 1},
    {"movie": "Jacob's Ladder", "weight": 1},
    {"movie": "Jerry Maguire", "weight": 1},
    {"movie": "Joker", "weight": 1},
    {"movie": "John Wick", "weight": 1},
    {"movie": "Jurassic Park", "weight": 1},
    {"movie": "Kingdom of Heaven", "weight": 1},
    {"movie": "Law Abiding Citizen", "weight": 1},
    {"movie": "Les Miserables", "weight": 1},
    {"movie": "League Of Extraordinary Gentlemen", "weight": 1},
    {"movie": "Life of Pi", "weight": 1},
    {"movie": "Limitless", "weight": 1},
    {"movie": "Lost in Translation", "weight": 1},
    {"movie": "Margin Call", "weight": 1},
    {"movie": "Memento", "weight": 1},
    {"movie": "Miss Peregrine's Home for Peculiar Children", "weight": 1},
    {"movie": "Mean Girls", "weight": 1},
    {"movie": "Meet Joe Black", "weight": 1},
    {"movie": "Men in Black I", "weight": 1},
    {"movie": "Men in Black II", "weight": 1},
    {"movie": "Men in Black III", "weight": 1},
    {"movie": "Metropolis 1927", "weight": 1},
    {"movie": "Moneyball", "weight": 1},
    {"movie": "Mr. Nobody (Extended Director's Cut)", "weight": 1},
    {"movie": "My Neighbor Totoro", "weight": 1},
    {"movie": "Napoleon Dynamite", "weight": 1},
    {"movie": "Nick & Norah's Infinite Playlist", "weight": 1},
    {"movie": "O Brother, Where Art Thou?", "weight": 1},
    {"movie": "October Sky", "weight": 1},
    {"movie": "Office Space", "weight": 1},
    {"movie": "One Flew Over The Cuckoo's Nest", "weight": 1},
    {"movie": "Oppenheimer", "weight": 1},
    {"movie": "Prisoners", "weight": 1},
    {"movie": "Prometheus", "weight": 1},
    {"movie": "Pulp Fiction", "weight": 1},
    {"movie": "Red Dog", "weight": 1},
    {"movie": "Remember the Titans", "weight": 1},
    {"movie": "Requiem for a Dream", "weight": 1},
    {"movie": "Rise of the Guardians", "weight": 1},
    {"movie": "Rise of the Planet of the Apes", "weight": 1},
    {"movie": "Rounders", "weight": 1},
    {"movie": "Scott Pilgrim vs. The World", "weight": 1},
    {"movie": "Seven (1995)", "weight": 1},
    {"movie": "Shrek", "weight": 1},
    {"movie": "Shrek 2", "weight": 1},
    {"movie": "Shrek the Third", "weight": 1},
    {"movie": "Shrek Forever After", "weight": 1},
    {"movie": "Shutter Island", "weight": 1},
    {"movie": "Signs", "weight": 1},
    {"movie": "Snowpiercer", "weight": 1},
    {"movie": "Spaceballs", "weight": 1},
    {"movie": "Spider-Man: Into The Spider-Verse", "weight": 1},
    {"movie": "Spirited Away", "weight": 1},
    {"movie": "Star Trek", "weight": 1},
    {"movie": "Star Trek Beyond", "weight": 1},
    {"movie": "Star Trek Into Darkness", "weight": 1},
    {"movie": "Sucker Punch", "weight": 1},
    {"movie": "Superbad Unrated", "weight": 1},
    {"movie": "Taxi Driver", "weight": 1},
    {"movie": "Tenacious D in The Pick of Destiny", "weight": 1},
    {"movie": "Tenet", "weight": 1},
    {"movie": "The Adjustment Bureau", "weight": 1},
    {"movie": "The Batman", "weight": 1},
    {"movie": "The Babadook", "weight": 1},
    {"movie": "The Blind Side", "weight": 1},
    {"movie": "The Big Lebowski", "weight": 1},
    {"movie": "The Big Short", "weight": 1},
    {"movie": "The Book of Eli", "weight": 1},
    {"movie": "The Butterfly Effect", "weight": 1},
    {"movie": "The Chronicles Of Narnia: The Lion, the Witch & the Wardrobe", "weight": 1},
    {"movie": "The Dark Knight", "weight": 1},
    {"movie": "The Dark Knight Rises", "weight": 1},
    {"movie": "The Devil Wears Prada", "weight": 1},
    {"movie": "The Fast & Furious: Tokyo Drift", "weight": 1},
    {"movie": "The Fast and the Furious", "weight": 1},
    {"movie": "The Fault In Our Stars", "weight": 1},
    {"movie": "The Fifth Element", "weight": 1},
    {"movie": "The Giver", "weight": 1},
    {"movie": "The Goonies", "weight": 1},
    {"movie": "The Green Mile", "weight": 1},
    {"movie": "The Hobbit: An Unexpected Journey", "weight": 1},
    {"movie": "The Hobbit: The Battle of the Five Armies", "weight": 1},
    {"movie": "The Hobbit: The Desolation of Smaug", "weight": 1},
    {"movie": "The House That Jack Built (Director's Cut)", "weight": 1},
    {"movie": "The Hummingbird Project", "weight": 1},
    {"movie": "THE HUNGER GAMES", "weight": 1},
    {"movie": "The Little Prince", "weight": 1},
    {"movie": "The Lord of the Rings: The Fellowship of the Ring", "weight": 1},
    {"movie": "The Lord of the Rings: The Return of the King", "weight": 1},
    {"movie": "The Lord of the Rings: The Two Towers", "weight": 1},
    {"movie": "The Matrix", "weight": 1},
    {"movie": "The Matrix Reloaded", "weight": 1},
    {"movie": "The Matrix Revolutions", "weight": 1},
    {"movie": "The Notebook", "weight": 1},
    {"movie": "The Outsiders", "weight": 1},
    {"movie": "The Pursuit of Happyness", "weight": 1},
    {"movie": "The Shawshank Redemption", "weight": 1},
    {"movie": "The Social Network", "weight": 1},
    {"movie": "The Signal", "weight": 1},
    {"movie": "The Strangers", "weight": 1},
    {"movie": "The Theory of Everything", "weight": 1},
    {"movie": "The Thirteenth Floor", "weight": 1},
    {"movie": "The Truman Show", "weight": 1},
    {"movie": "The Wave", "weight": 1},
    {"movie": "The Wizard of Oz (1939)", "weight": 1},
    {"movie": "The Wolf of Wall Street", "weight": 1},
    {"movie": "Titanic", "weight": 1},
    {"movie": "Too Big To Fail", "weight": 1},
    {"movie": "Toy Story", "weight": 1},
    {"movie": "Trading Places", "weight": 1},
    {"movie": "Transformers", "weight": 1},
    {"movie": "Tron: Legacy", "weight": 1},
    {"movie": "Troy", "weight": 1},
    {"movie": "Turbo Kid", "weight": 1},
    {"movie": "Twilight", "weight": 1},
    {"movie": "Under the Silver Lake", "weight": 1},
    {"movie": "Vacancy", "weight": 1},
    {"movie": "Vanilla Sky", "weight": 1},
    {"movie": "WALL-E", "weight": 1},
    {"movie": "Wall Street", "weight": 1},
    {"movie": "Wall Street: Money Never Sleeps", "weight": 1},
    {"movie": "Warm Bodies", "weight": 1},
    {"movie": "Watchmen", "weight": 1},
    {"movie": "Wayne's World", "weight": 1},
    {"movie": "Winter's Tale", "weight": 1},
    {"movie": "Zodiac", "weight": 1},
    {"movie": "Zombieland", "weight": 1},
    {"movie": "Something Random", "weight": 10},
    {"movie": "Something From Watchlist", "weight": 10}
]

# Generate the movies and weights list
movies = [entry["movie"] for entry in movies_with_weights]
weights = [entry["weight"] for entry in movies_with_weights]

# Select a random movie using the weights
selected_movie = random.choices(movies, weights=weights, k=1)[0]

# Display the selected movie
print(f"You should watch: {selected_movie}")
