import random

# Define your list of movies here
movies = [
    "20,000 Leagues Under the Sea",
    "2001: A Space Odyssey",
    "300",
    "8 Mile",
    "A Beautiful Mind",
    "A Christmas Story",
    "A Nightmare on Elm Street (2010)",
    "A Scanner Darkly",
    "Alice in Wonderland (2010)",
    "Alien: Covenant",
    "Almost Famous",
    "American Beauty",
    "American Psycho",
    "Apocalypoto",
    "Arrival",
    "August Rush",
    "Back to the Future",
    "Back to the Future II",
    "Back to the Future Part III",
    "Baraka",
    "Batman Begins",
    "Being John Malcovich",
    "Big",
    "Big Hero 6",
    "Blade Runner 2049",
    "Blade Runner: The Final Cut",
    "Boiler Room",
    "Bridge to Tarabithia",
    "Constantine",
    "Contact",
    "Divergent",
    "Donnie Darko",
    "Dr. Seuss' How the Grinch Stole Christmas",
    "Dracula Untold",
    "Dune",
    "Eternal Sunshine of the spotless mind",
    "Ex Machina",
    "Fern Gully",
    "Fight Club",
    "Forrest Gump",
    "Get Rich Or Die Tryin'",
    "Gladiator",
    "Gone in Sixty Seconds",
    "Good Will Hunting",
    "Goodfellas",
    "Grandma's Boy UNRATED",
    "Guardians of the Galaxy",
    "Hardball",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Deathly Hallows: Part 1",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Half-Blood Prince",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Sorcerer's Stone",
    "Hellboy",
    "Home Alone",
    "Home Alone 2: Lost In New York",
    "Howl's Moving Castle",
    "Inception",
    "Incident in a Ghostland",
    "Independence Day",
    "Inglorious Basterds",
    "Inside Job",
    "Interstellar",
    "IP Man",
    "Iron Giant",
    "IT",
    "IT Chapter Two",
    "It Follows",
    "Jacob's Ladder",
    "Jerry Maguire",
    "Joker",
    "John Wick",
    "Jurassic Park",
    "Kingdom of Heaven",
    "Law Abiding Citizen",
    "Les Miserables",
    "League Of Extraordinary Gentlemen",
    "Life of Pi",
    "Limitless",
    "Lost in Translation",
    "Margin Call",
    "Memento",
    "Miss Peregrine's Home for Peculiar Children",
    "Mean Girls",
    "Meet Joe Black",
    "Men in Black I",
    "Men in Black II",
    "Men in Black III",
    "Metropolis 1927",
    "Moneyball",
    "Mr. Nobody (Extended Director's Cut)",
    "My Neighbor Totoro",
    "Napoleon Dynamite",
    "Nick & Norah's Infinite Playlist",
    "O Brother, Where Art Thou?",
    "October Sky",
    "Office Space",
    "One Flew Over The Cuckoo's Nest",
    "Oppenheimer",
    "Prisoners",
    "Prometheus",
    "Pulp Fiction",
    "Red Dog",
    "Remember the Titans",
    "Requiem for a Dream",
    "Rise of the Guardians",
    "Rise of the Planet of the Apes",
    "Rounders",
    "Scott Pilgrim vs. The World",
    "Seven (1995)",
    "Shrek",
    "Shrek 2",
    "Shrek the Third",
    "Shrek Forever After",
    "Shutter Island",
    "Signs",
    "Snowpiercer",
    "Spaceballs",
    "Spider-Man: Into The Spider-Verse",
    "Spirited Away",
    "Star Trek",
    "Star Trek Beyond",
    "Star Trek Into Darkness",
    "Sucker Punch",
    "Superbad Unrated",
    "Taxi Driver",
    "Tenacious D in The Pick of Destiny",
    "Tenet",
    "The Adjustment Bureau",
    "The Batman",
    "The Babadook",
    "The Blind Side",
    "The Big Lebowski",
    "The Big Short",
    "The Book of Eli",
    "The Chronicles Of Narnia: The Lion, the Witch & the Wardrobe",
    "The Dark Knight",
    "The Dark Knight Rises",
    "The Devil Wears Prada",
    "The Fast & Furious: Tokyo Drift",
    "The Fast and the Furious",
    "The Fault In Our Stars",
    "The Fifth Element",
    "The Giver",
    "The Goonies",
    "The Green Mile",
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: The Battle of the Five Armies",
    "The Hobbit: The Desolation of Smaug",
    "The House That Jack Built (Director's Cut)",
    "The Hummingbird Project",
    "THE HUNGER GAMES",
    "The Little Prince",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Return of the King",
    "The Lord of the Rings: The Two Towers",
    "The Matrix",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "The Notebook",
    "The Outsiders",
    "The Pursuit of Happyness",
    "The Shawshank Redemption",
    "The Social Network",
    "The Signal",
    "The Strangers",
    "The Theory of Everything",
    "The Thirteenth Floor",
    "The Truman Show",
    "The Wave",
    "The Wizard of Oz (1939)",
    "The Wolf of Wall Street",
    "Titanic",
    "Too Big To Fail",
    "Toy Story",
    "Trading Places",
    "Transformers",
    "Tron: Legacy",
    "Troy",
    "Turbo Kid",
    "Twilight",
    "Under the Silver Lake",
    "Vacancy",
    "Vanilla Sky",
    "WALL-E",
    "Wall Street",
    "Wall Street: Money Never Sleeps",
    "Warm Bodies",
    "Watchmen",
    "Wayne's World",
    "Winter's Tale",
    "Zodiac",
    "Zombieland",
    "Something From Watchlist"
]

# Select a random movie
selected_movie = random.choice(movies)

# Display the selected movie
print(f"You should watch: {selected_movie}")
